language: android


android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-24.0.3

    # The SDK version used to compile your project
    - android-24

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    # - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-23
    - sys-img-x86-android-24

   licenses: 
    - android-sdk-license-.+
    - google-gdk-license-.+

jdk:
  - oraclejdk8

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8


before_script:
    - wget http://downloads.gradle.org/distributions/gradle-3.3-bin.zip
    - unzip gradle-3.3-bin.zip
    - export GRADLE_HOME=$PWD/gradle-3.3
    - export PATH=$GRADLE_HOME/bin:$PATH

script:
  - android list target
  - gradle wrapper
  - ./gradlew build -x lint
  - ./gradlew connectedAndroidTest
